# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Tue Apr 15 08:59:50 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1237, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setEnabled(False)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(2, -1, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.bar1 = QtGui.QWidget(self.centralWidget)
        self.bar1.setMinimumSize(QtCore.QSize(0, 50))
        self.bar1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bar1.setObjectName(_fromUtf8("bar1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.bar1)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.textSearch = QtGui.QLabel(self.bar1)
        self.textSearch.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textSearch.sizePolicy().hasHeightForWidth())
        self.textSearch.setSizePolicy(sizePolicy)
        self.textSearch.setMinimumSize(QtCore.QSize(0, 0))
        self.textSearch.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textSearch.setObjectName(_fromUtf8("textSearch"))
        self.horizontalLayout_2.addWidget(self.textSearch)
        self.editSearch = QtGui.QLineEdit(self.bar1)
        self.editSearch.setMinimumSize(QtCore.QSize(0, 0))
        self.editSearch.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editSearch.setObjectName(_fromUtf8("editSearch"))
        self.horizontalLayout_2.addWidget(self.editSearch)
        self.searchResult = QtGui.QLabel(self.bar1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchResult.sizePolicy().hasHeightForWidth())
        self.searchResult.setSizePolicy(sizePolicy)
        self.searchResult.setMinimumSize(QtCore.QSize(600, 0))
        self.searchResult.setMaximumSize(QtCore.QSize(600, 16777215))
        self.searchResult.setObjectName(_fromUtf8("searchResult"))
        self.horizontalLayout_2.addWidget(self.searchResult)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.addWidget(self.bar1)
        self.bar2 = QtGui.QWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar2.sizePolicy().hasHeightForWidth())
        self.bar2.setSizePolicy(sizePolicy)
        self.bar2.setMinimumSize(QtCore.QSize(1020, 220))
        self.bar2.setMaximumSize(QtCore.QSize(16777215, 220))
        self.bar2.setObjectName(_fromUtf8("bar2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.bar2)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.graph1 = QtGui.QLabel(self.bar2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph1.sizePolicy().hasHeightForWidth())
        self.graph1.setSizePolicy(sizePolicy)
        self.graph1.setMinimumSize(QtCore.QSize(500, 200))
        self.graph1.setMaximumSize(QtCore.QSize(500, 200))
        self.graph1.setObjectName(_fromUtf8("graph1"))
        self.horizontalLayout_3.addWidget(self.graph1)
        self.graph2 = QtGui.QLabel(self.bar2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph2.sizePolicy().hasHeightForWidth())
        self.graph2.setSizePolicy(sizePolicy)
        self.graph2.setMinimumSize(QtCore.QSize(500, 200))
        self.graph2.setMaximumSize(QtCore.QSize(500, 200))
        self.graph2.setObjectName(_fromUtf8("graph2"))
        self.horizontalLayout_3.addWidget(self.graph2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.bar2)
        self.bar3 = QtGui.QWidget(self.centralWidget)
        self.bar3.setMinimumSize(QtCore.QSize(0, 50))
        self.bar3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bar3.setObjectName(_fromUtf8("bar3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.bar3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.used = QtGui.QCheckBox(self.bar3)
        self.used.setObjectName(_fromUtf8("used"))
        self.horizontalLayout_4.addWidget(self.used)
        self.editBegin = QtGui.QLineEdit(self.bar3)
        self.editBegin.setMinimumSize(QtCore.QSize(50, 30))
        self.editBegin.setMaximumSize(QtCore.QSize(50, 30))
        self.editBegin.setText(_fromUtf8(""))
        self.editBegin.setObjectName(_fromUtf8("editBegin"))
        self.horizontalLayout_4.addWidget(self.editBegin)
        self.textTo = QtGui.QLabel(self.bar3)
        self.textTo.setMinimumSize(QtCore.QSize(80, 30))
        self.textTo.setMaximumSize(QtCore.QSize(80, 30))
        self.textTo.setObjectName(_fromUtf8("textTo"))
        self.horizontalLayout_4.addWidget(self.textTo)
        self.editEnd = QtGui.QLineEdit(self.bar3)
        self.editEnd.setMinimumSize(QtCore.QSize(50, 30))
        self.editEnd.setMaximumSize(QtCore.QSize(50, 30))
        self.editEnd.setObjectName(_fromUtf8("editEnd"))
        self.horizontalLayout_4.addWidget(self.editEnd)
        spacerItem2 = QtGui.QSpacerItem(619, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_4.setStretch(4, 1)
        self.verticalLayout_2.addWidget(self.bar3)
        self.textDisplay = QtGui.QTextEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textDisplay.sizePolicy().hasHeightForWidth())
        self.textDisplay.setSizePolicy(sizePolicy)
        self.textDisplay.setMinimumSize(QtCore.QSize(1020, 0))
        self.textDisplay.setMaximumSize(QtCore.QSize(1020, 16777215))
        self.textDisplay.setReadOnly(True)
        self.textDisplay.setAcceptRichText(True)
        self.textDisplay.setObjectName(_fromUtf8("textDisplay"))
        self.verticalLayout_2.addWidget(self.textDisplay)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1237, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(206, 190))
        self.dockWidget_2.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidget_2.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.selectAll = QtGui.QPushButton(self.dockWidgetContents_2)
        self.selectAll.setObjectName(_fromUtf8("selectAll"))
        self.verticalLayout_3.addWidget(self.selectAll)
        self.deselectAll = QtGui.QPushButton(self.dockWidgetContents_2)
        self.deselectAll.setObjectName(_fromUtf8("deselectAll"))
        self.verticalLayout_3.addWidget(self.deselectAll)
        self.textsList = QtGui.QListWidget(self.dockWidgetContents_2)
        self.textsList.setMinimumSize(QtCore.QSize(200, 0))
        self.textsList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textsList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.textsList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.textsList.setObjectName(_fromUtf8("textsList"))
        self.verticalLayout_3.addWidget(self.textsList)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.openAction = QtGui.QAction(MainWindow)
        self.openAction.setObjectName(_fromUtf8("openAction"))
        self.exitAction = QtGui.QAction(MainWindow)
        self.exitAction.setObjectName(_fromUtf8("exitAction"))
        self.menuFile.addAction(self.openAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exitAction)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Analyse fréquentielle de textes", None, QtGui.QApplication.UnicodeUTF8))
        self.textSearch.setText(QtGui.QApplication.translate("MainWindow", "Motif :", None, QtGui.QApplication.UnicodeUTF8))
        self.searchResult.setText(QtGui.QApplication.translate("MainWindow", "Résultat", None, QtGui.QApplication.UnicodeUTF8))
        self.graph1.setText(QtGui.QApplication.translate("MainWindow", "Graphe 1", None, QtGui.QApplication.UnicodeUTF8))
        self.graph2.setText(QtGui.QApplication.translate("MainWindow", "Graphe 2", None, QtGui.QApplication.UnicodeUTF8))
        self.used.setText(QtGui.QApplication.translate("MainWindow", "Utiliser ce texte du vers", None, QtGui.QApplication.UnicodeUTF8))
        self.textTo.setText(QtGui.QApplication.translate("MainWindow", "jusqu\'au vers", None, QtGui.QApplication.UnicodeUTF8))
        self.textDisplay.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Textes ouverts", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAll.setText(QtGui.QApplication.translate("MainWindow", "Tout sélectionner", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAll.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.deselectAll.setText(QtGui.QApplication.translate("MainWindow", "Tout déselectionner", None, QtGui.QApplication.UnicodeUTF8))
        self.deselectAll.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.openAction.setText(QtGui.QApplication.translate("MainWindow", "&Ouvrir", None, QtGui.QApplication.UnicodeUTF8))
        self.openAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "Ouvrir un fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.openAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setText(QtGui.QApplication.translate("MainWindow", "&Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quitter le programme", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))

